### ISSUE TITLE
Possible to specify language of download?

### ISSUE THREAD

**Issue by gelsas** [denniseffing/series-scraper#1]
Possible to specify language of download?

also do i need to manually add the name of the tv show each time in the config or will it check the tv shows on my plex server and search automatically for the missing episodes then ?

**Comment by denniseffing** [comment]
As of now, you can't specify the language of the episodes.

Yes, you have to manually add the name of the TV show in the config.
To be honest, the current implementation is still pretty rudimentary. I didn't have the time to expand it yet but I will propably get back to this project after the end of this month.

Until then, feel free to create a pull request.

**Comment by denniseffing** [comment]
@gelsas Sorry that it took so long. You can now specify the language of the episodes.
